services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "pg_password"
    ports:
      - "5432:5432"
    networks:
      - postgres-network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "pg_password"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - postgres-network

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass redis_password

networks:
  postgres-network:
    driver: bridge
