"""order

Revision ID: 60ed2774255e
Revises: 9b5b28a88a3f
Create Date: 2023-08-31 20:07:11.786386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '60ed2774255e'
down_revision: Union[str, None] = '9b5b28a88a3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
        sa.Column('client_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('order_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('total_price', sa.Float(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('finished_at', sa.DateTime(), nullable=True),
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_client_name'), 'order', ['client_name'], unique=False)
    op.create_index(op.f('ix_order_order_key'), 'order', ['order_key'], unique=False)
    op.create_table('order_food',
    sa.Column('order_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('food_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.Column('observation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('price', sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(['food_id'], ['food.id'], ),
        sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
        sa.PrimaryKeyConstraint('order_id', 'food_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_food')
    op.drop_index(op.f('ix_order_order_key'), table_name='order')
    op.drop_index(op.f('ix_order_client_name'), table_name='order')
    op.drop_table('order')
    # ### end Alembic commands ###
